import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1c1b',
        'on-primary-container': '#978a85',
        'on-background': '#1a1c1b',
        'on-secondary-fixed': '#261900',
        secondary: '#705c32',
        primary: '#160f0c',
        tertiary: '#0c1114',
        'surface-tint': '#675c57',
        'surface-container-low': '#f4f3f1',
        'error-container': '#ffdad6',
        'tertiary-container': '#212629',
        surface: '#faf9f7',
        'on-error': '#ffffff',
        background: '#faf9f7',
        'primary-fixed': '#efdfd9',
        'on-surface-variant': '#4e4541',
        'surface-variant': '#e3e2e0',
        'tertiary-fixed-dim': '#c3c7ca',
        'on-secondary-container': '#766237',
        'surface-container-highest': '#e3e2e0',
        'on-primary-fixed-variant': '#4e4540',
        'surface-container': '#efeeec',
        'secondary-fixed-dim': '#dec390',
        'primary-container': '#2c2420',
        outline: '#7f7570',
        'on-tertiary-fixed-variant': '#42474a',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'on-primary-fixed': '#211a16',
        'on-secondary-fixed-variant': '#57441d',
        'inverse-on-surface': '#f1f1ef',
        'on-tertiary-container': '#888d90',
        'inverse-surface': '#2f3130',
        'secondary-container': '#fcdfaa',
        'on-tertiary-fixed': '#171c1f',
        'on-secondary': '#ffffff',
        'surface-bright': '#faf9f7',
        'surface-dim': '#dadad8',
        'surface-container-high': '#e9e8e6',
        'outline-variant': '#d1c4be',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#dfe3e6',
        'secondary-fixed': '#fcdfaa',
        'inverse-primary': '#d2c4bd',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#d2c4bd',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '32px',
        'margin-page': '64px',
        'stack-md': '16px',
        'section-gap': '120px',
        gutter: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'label-sm': ['"Work Sans"', 'sans-serif'],
        'display-xl': ['Manrope', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-sm': [
          '12px',
          { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'display-xl': [
          '48px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
